name: Continous Deployment

on:
  workflow_run:
    workflows: ["Continous Integration"]
    types:
      - completed

jobs:
  deploy:
    name: Deployment job
    uses: nl-squad/nl-cod2-workflows/.github/workflows/deploy.yml@main
    with:
      profile: default
    secrets: inherit

  build-000empty:
    name: Build 000empty.iwd
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute build-000empty.sh remotely
      run: |
        project_definition="project-definition.json"
        if [ ! -f $project_definition ]; then
            echo "Error: $project_definition doesn't exist. Please use mynl CLI tool from within NL directory."
            exit 1
        fi

        function extract_value_or_exit() {
          local key=$1
          local value=$(jq -r "$key" "$project_definition")

          if [ "$value" = "null" ]; then
              echo "Error: $key not found in the $project_definition file."
              exit 1
          fi

          echo "$value"
        }

        ###

        profile=${{ inputs.profile }}
        connection_address=$(extract_value_or_exit '.connection.address')
        connection_user=$(extract_value_or_exit '.connection.user')
        connection_key_path=~/private_key
        echo "Starting ~/cod2/library/build-000empty.sh, host: $connection_user@$connection_address"

        echo "${{ secrets.VPS_PRIVATE_KEY }}" > $connection_key_path
        chmod 600 $connection_key_path
        echo "Private key set up"

        ssh -i $connection_key_path -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $connection_user@$connection_address "\
          echo 'Executing ~/cod2/library/build-000empty.sh' && \
          ~/cod2/library/build-000empty.sh"

        rm -f $connection_key_path
      env:
        PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}

# Done: Support for iwds path nl-cli
# Done: ./src/scripts -> ~/cod2/library/scripts
# Done: ./src/iwds -> ~/cod2/library/iwds
# Get sha256sum of ~/cod2/library/iwds
# Compare with ~/cod2/library/iwds_sum
# Done: If not the same - build ~/cod2/library/000empty.iwd
# ./restart.sh - copy maps
# ./restart.sh - copy iwds
# ./restart.sh - copy 000empty.iwd
# ./restart.sh - restart docker-compose
