name: Remote Git Pull on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute remote Git pull on VPS
      run: |
        echo "1/7: Setting up private key..."
        echo "${{ secrets.VPS_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        echo "2/7: Connecting to VPS and deploying changes..."
        ssh -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ env.VPS_USERNAME }}@${{ env.VPS_ADDRESS }} "\
          echo '3/7: Changing directory to VPS_DIRECTORY...' && \
          cd ${{ env.VPS_DIRECTORY }} && \
          echo '4/7: Checking git initialization and setting up remote...' && \
          (test -d .git || git init) && \
          (git remote | grep -q '^origin$' || git remote add origin https://github.com/${GITHUB_REPOSITORY}.git) && \
          echo '5/7: Configuring GitHub token for authentication...' && \
          git config --local http.https://github.com/.extraheader 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' && \
          echo '6/7: Fetching latest changes...' && \
          git fetch && \
          echo '7/7: Resetting local branch to the commit' $GITHUB_SHA '...' && \
          git reset --hard ${{ GITHUB_SHA }} && \
          git clean -f -d && \
          echo 'Deployment complete!'"
        rm -f private_key
      env:
        PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
